### User 2 (testing app)
@tokenUser2 = f1d1cdbc-97f0-41c4-b206-051250684b19

### Insert a task

POST http://localhost:8000/tasks HTTP/2
Content-Type: application/json
Authorization: Bearer {{tokenUser2}}

{
    "title": "Study HTTP",
    "description": "Read the documentation."
}

### Insert a task

POST http://localhost:8000/tasks HTTP/2
Content-Type: application/json
Authorization: Bearer {{tokenUser2}}

{
    "title": "Do class exercise",
    "description": "Implement the task application."
}

### Get all tasks

GET http://localhost:8000/tasks HTTP/2
Authorization: Bearer {{tokenUser2}}

### Get task 1

GET http://localhost:8000/tasks/1 HTTP/2
Authorization: Bearer {{tokenUser2}}

### Update task 1

PUT http://localhost:8000/tasks/1 HTTP/2
Content-Type: application/json
Authorization: Bearer {{tokenUser2}}

{
    "title": "Do class exercise",
    "description": "Reimplement the task application!!!"
}

### Delete task 7

DELETE http://localhost:8000/tasks/7 HTTP/2
Authorization: Bearer {{tokenUser2}}
