export const INTERNAL_ERROR_CODES = {
    INVALID_BODY: 1,
    INVALID_QUERY: 2,
    INVALID_PARAMETER: 3,
    TASK_NOT_FOUND: 4,
    USER_NOT_FOUND: 5,
    MISSING_TOKEN: 6,
    NOT_AUTHORIZED: 7,
    MISSING_PARAMETER: 8,
    USER_ALREADY_EXISTS: 9
};