export const INTERNAL_ERROR_CODES = {
    SERVER_ERROR: 1,
    INVALID_USER: 2,
    INVALID_TASK: 3,
    INVALID_QUERY: 4,
    INVALID_PARAMETER: 5,
    TASK_NOT_FOUND: 6,
    USER_NOT_FOUND: 7,
    USER_ALREADY_EXISTS: 8,
    MISSING_PARAMETER: 9,
    MISSING_TOKEN: 10,
    NOT_AUTHORIZED: 11
};